"""Per-package conftest for extraction-pipeline tests.

Provides path fixtures that point at synthetic firmware binaries
generated by ``tests/extraction/fixtures/``. Each fixture is built
into a per-test ``tmp_path`` so tests can mutate the binary without
tainting siblings.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tests.extraction.fixtures import (
    synthetic_microcode,
    synthetic_option_rom,
    synthetic_uefi_volume,
)


@pytest.fixture()
def synthetic_uefi_volume_path(tmp_path: Path) -> Path:
    """Path to a freshly built synthetic UEFI PI volume binary."""
    return synthetic_uefi_volume.build(tmp_path)


@pytest.fixture()
def synthetic_uefi_volume_with_tiano_path(tmp_path: Path) -> Path:
    """Synthetic UEFI PI volume with one Tiano-compressed FFS file."""
    return synthetic_uefi_volume.build(
        tmp_path,
        filename="uefi_volume_tiano.bin",
        with_tiano_section=True,
    )


@pytest.fixture()
def synthetic_uefi_volume_with_lzma_path(tmp_path: Path) -> Path:
    """Synthetic UEFI PI volume with one LZMA-compressed FFS file."""
    return synthetic_uefi_volume.build(
        tmp_path,
        filename="uefi_volume_lzma.bin",
        with_lzma_section=True,
    )


@pytest.fixture()
def synthetic_uefi_volume_with_corrupt_compressed_path(tmp_path: Path) -> Path:
    """Synthetic UEFI PI volume with one Tiano-marked, garbage-payload FFS file."""
    return synthetic_uefi_volume.build(
        tmp_path,
        filename="uefi_volume_corrupt.bin",
        with_corrupt_compressed_section=True,
    )


@pytest.fixture()
def synthetic_option_rom_path(tmp_path: Path) -> Path:
    """Path to a freshly built synthetic two-image PCI option ROM."""
    return synthetic_option_rom.build(tmp_path)


@pytest.fixture()
def synthetic_microcode_path(tmp_path: Path) -> Path:
    """Path to a freshly built synthetic two-blob microcode update."""
    return synthetic_microcode.build(tmp_path)
